import React, { useState, useEffect } from 'react'
import { Box, Typography, IconButton, Tooltip } from '@mui/material'
import { NavLink } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Home, LayoutDashboard, SprayCan, Sparkles, ChevronLeft, ChevronRight, Lightbulb } from 'lucide-react'
import Brand from '../ui/Brand'
import { colors, spacing, typography, radius } from '../../utils/tokens'

const NAV_ITEMS = [
  { id: 'home', label: 'Home', tag: 'Landing', to: '/', icon: <Home size={19} /> },
  { id: 'workspace', label: 'Workspace', tag: 'Inspector', to: '/workspace', icon: <LayoutDashboard size={19} /> },
  { id: 'cleaner', label: 'Privacy Cleaner', tag: 'Sanitizer', to: '/privacy-cleaner', icon: <SprayCan size={19} /> },
]

const FOOTER_ITEMS = [
  { label: 'Features', to: '/features', icon: <Sparkles size={19} /> },
]

const TIPS = [
  'Images generated by ChatGPT may contain C2PA Content Credentials.',
  'Screenshots usually do not contain EXIF metadata.',
  'Social media platforms often remove image metadata.',
  'Use the Privacy Cleaner before sharing sensitive images.',
  'Images with verified C2PA provide a trusted provenance trail.',
]

/**
 * Desktop sidebar matching the ProofLens Analysis Workspace.
 * Supports expandable (240px) / collapsed icon mode (68px), engine status, formats, and tips.
 */
export default function AppSidebar() {
  const [collapsed, setCollapsed] = useState(false)
  const [tipIndex, setTipIndex] = useState(0)

  useEffect(() => {
    const timer = setInterval(() => {
      setTipIndex((prev) => (prev + 1) % TIPS.length)
    }, 5000)
    return () => clearInterval(timer)
  }, [])

  const toggleCollapse = () => setCollapsed((prev) => !prev)

  const renderItem = (item) => {
    const isExternal = item.external
    const linkProps = isExternal
      ? { component: 'a', href: item.to, target: '_blank', rel: 'noreferrer' }
      : { to: item.to }

    const styles = ({ isActive }) => ({
      display: 'flex',
      alignItems: 'center',
      gap: collapsed ? 0 : spacing.sm,
      justifyContent: collapsed ? 'center' : 'flex-start',
      px: collapsed ? 1 : spacing.sm,
      py: 1,
      textDecoration: 'none',
      borderRadius: radius.default,
      fontWeight: isActive ? 600 : 500,
      bgcolor: isActive ? colors.secondaryContainer : 'transparent',
      color: isActive ? colors.onSecondaryContainer : colors.onSurfaceVariant,
      fontSize: '13px',
      position: 'relative',
      '&:hover': {
        bgcolor: isActive ? colors.secondaryContainer : colors.surfaceContainerHigh,
        color: isActive ? colors.onSecondaryContainer : colors.onSurface,
      },
      transition: 'all 0.2s ease',
    })

    const linkEl = (
      <NavLink
        key={item.to}
        to={item.to}
        end={item.to === '/'}
        style={({ isActive }) => ({
          ...styles({ isActive }),
        })}
        {...linkProps}
      >
        {item.icon}
        {!collapsed && (
          <>
            <Typography sx={{ fontSize: '13px', fontWeight: 'inherit', flex: 1 }}>{item.label}</Typography>
            {item.tag && (
              <Box
                sx={{
                  px: 0.75,
                  py: 0.25,
                  borderRadius: radius.sm,
                  fontSize: '10px',
                  fontWeight: 600,
                  bgcolor: 'rgba(255, 255, 255, 0.06)',
                  color: colors.outline,
                  letterSpacing: '0.04em',
                  textTransform: 'uppercase',
                }}
              >
                {item.tag}
              </Box>
            )}
          </>
        )}
      </NavLink>
    )

    if (collapsed) {
      return (
        <Tooltip key={item.to} title={item.label} placement="right" arrow>
          <Box sx={{ width: '100%' }}>{linkEl}</Box>
        </Tooltip>
      )
    }

    return linkEl
  }

  return (
    <Box
      component="nav"
      aria-label="Main navigation"
      sx={{
        display: { xs: 'none', md: 'flex' },
        flexDirection: 'column',
        height: '100%',
        p: collapsed ? 1.5 : spacing.md,
        bgcolor: colors.surfaceContainerLowest,
        width: collapsed ? 68 : 240,
        borderRight: `1px solid rgba(145, 94, 255, 0.18)`,
        flexShrink: 0,
        zIndex: 20,
        transition: 'width 0.25s cubic-bezier(0.4, 0, 0.2, 1), padding 0.25s ease',
      }}
    >
      {/* Top Header: Brand + Collapse Button */}
      <Box sx={{ mb: 2, display: 'flex', alignItems: 'center', justifyContent: collapsed ? 'center' : 'space-between', px: collapsed ? 0 : spacing.xs }}>
        {!collapsed ? (
          <NavLink to="/" style={{ textDecoration: 'none', color: 'inherit' }}>
            <Brand size={26} />
          </NavLink>
        ) : (
          <NavLink to="/" style={{ textDecoration: 'none' }}>
            <Box sx={{ width: 32, height: 32, borderRadius: radius.sm, bgcolor: colors.primary, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#131313', fontWeight: 800, fontSize: '16px' }}>
              P
            </Box>
          </NavLink>
        )}

        <IconButton
          onClick={toggleCollapse}
          size="small"
          aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"}
          sx={{
            color: colors.outlineVariant,
            '&:hover': { color: colors.onSurface, bgcolor: colors.surfaceContainerHigh },
          }}
        >
          {collapsed ? <ChevronRight size={16} /> : <ChevronLeft size={16} />}
        </IconButton>
      </Box>

      {/* Main Nav Items & Content (Fills height smoothly) */}
      <Box
        sx={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          gap: 2,
          overflowY: 'auto',
          my: 1,
        }}
      >
        {/* Navigation Section */}
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
          {!collapsed && (
            <Typography
              sx={{
                fontSize: '10px',
                fontWeight: 700,
                letterSpacing: '0.08em',
                color: colors.outline,
                textTransform: 'uppercase',
                px: spacing.xs,
              }}
            >
              Tools & Workspaces
            </Typography>
          )}

          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
            {NAV_ITEMS.map(renderItem)}
          </Box>
        </Box>

        {/* Sidebar Cards Container (anchors & expands to fill full vertical space) */}
        {!collapsed && (
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.75, mt: 'auto' }}>
            {/* Rotating Tips Card */}
            <Box
              sx={{
                p: 2,
                borderRadius: radius.md,
                bgcolor: colors.surfaceContainerLow,
                border: `1px solid ${colors.outlineVariant}20`,
                display: 'flex',
                flexDirection: 'column',
                gap: 1.25,
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <Typography sx={{ fontSize: '11px', fontWeight: 600, color: colors.onSurface, display: 'flex', alignItems: 'center', gap: 1 }}>
                  <Lightbulb size={14} color="#f59e0b" /> Tips
                </Typography>
                <Typography sx={{ fontSize: '9px', color: colors.outline, fontWeight: 500 }}>
                  {tipIndex + 1}/{TIPS.length}
                </Typography>
              </Box>

              <Typography
                key={tipIndex}
                component={motion.p}
                initial={{ opacity: 0, y: 3 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
                sx={{ fontSize: '11px', color: colors.onSurfaceVariant, lineHeight: 1.45, margin: 0 }}
              >
                {TIPS[tipIndex]}
              </Typography>
            </Box>
          </Box>
        )}
      </Box>

      {/* Footer Links */}
      <Box
        sx={{
          mt: 'auto',
          pt: 1.5,
          borderTop: '1px solid rgba(145, 94, 255, 0.18)',
          display: 'flex',
          flexDirection: 'column',
          gap: 0.5,
        }}
      >
        {FOOTER_ITEMS.map(renderItem)}
      </Box>
    </Box>
  )
}
